In [119]:
import pandas as pd
import numpy as np

# Stage 1.1: Data Import

In [93]:
#Import csv
file_path_transfers = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/transfers.csv"
transfers = pd.read_csv(file_path_transfers)

In [94]:
#Import Excel
file_path_national_teams = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/national_teams.xlsx"
national_teams = pd.read_excel(file_path_national_teams)

In [95]:
#Import json
file_path_trains = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/train.json"
train = pd.read_json(file_path_trains)
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39774 entries, 0 to 39773
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           39774 non-null  int64
 1   cuisine      39774 non-null  object
 2   ingredients  39774 non-null  object
dtypes: int64(1), object(2)
memory usage: 932.3+ KB

In [96]:
# Write to csv file
output_path = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/transfer_updated.csv"
transfers.to_csv(output_path)

In [97]:
# Write to excel file
output_path = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/national_teams_updated.xlsx"
national_teams.to_excel(output_path)

# Stage 1.2: Exploration

In [98]:
#Using head() to see first rows
transfers.head(5)

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,467994,2030-06-30,25/26,5621,749,Reggiana,FC Empoli,0.0,700000.0,Luca Belardinelli
1,739277,2027-05-30,26/27,42055,589,Genclik Gücü,Antalyaspor,0.0,NaN,Yannick Nkurunziza
2,401533,2026-12-31,26/27,2029,2423,Ceará SC,Santa Clara,0.0,1500000.0,Matheusinho
3,468256,2026-12-31,26/27,2035,16655,Avaí FC,Atlético-MG B,0.0,700000.0,Daniel Penha
4,541914,2026-12-31,26/27,713,1124,BATE Borisov,Fakel Voronezh,0.0,225000.0,Anton Kovalev

In [99]:
#Using tail() to see last rows
transfers.tail(5)

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
40203,61989,1997-07-01,97/98,55343,55341,VfR Rauxel Yth.,Habingh. Yth.,0.0,NaN,Michael Esser
40204,52480,1996-07-01,96/97,58405,54532,FC Penafiel You,Boavista CJ,NaN,NaN,Rúben Ribeiro
40205,68864,1996-07-01,96/97,79611,32804,Rijsoord Yth.,Sparta Youth,0.0,NaN,Kevin Strootman
40206,22141,1994-07-01,94/95,59178,29463,Castellammare,Sorrento Youth,NaN,NaN,Antonio Mirante
40207,61989,1993-07-01,93/94,55345,55343,A. Ickern Yth.,VfR Rauxel Yth.,0.0,NaN,Michael Esser

In [100]:
# Using info() to see null count and data type
transfers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40208 entries, 0 to 40207
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            40208 non-null  int64
 1   transfer_date        40208 non-null  object
 2   transfer_season      40208 non-null  object
 3   from_club_id         40208 non-null  int64
 4   to_club_id           40208 non-null  int64
 5   from_club_name       40208 non-null  object
 6   to_club_name         40208 non-null  object
 7   transfer_fee         25821 non-null  float64
 8   market_value_in_eur  24359 non-null  float64
 9   player_name          40208 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 3.1+ MB

In [101]:
# Using describe() to get numerical columns summary statistics
transfers.describe()

,player_id,from_club_id,to_club_id,transfer_fee,market_value_in_eur
count,4.020800e+04,40208.000000,40208.000000,2.582100e+04,2.435900e+04
mean,4.688484e+05,19052.409719,15539.312376,3.796877e+05,1.241725e+06
std,3.227540e+05,25353.137887,23147.742299,2.317581e+06,2.891459e+06
min,4.391000e+03,1.000000,1.000000,0.000000e+00,1.000000e+04
25%,1.936120e+05,1039.000000,828.750000,0.000000e+00,1.750000e+05
50%,3.986435e+05,7378.000000,4111.000000,0.000000e+00,4.000000e+05
75%,6.970670e+05,29228.000000,18936.000000,0.000000e+00,1.000000e+06
max,1.413094e+06,139411.000000,139411.000000,1.350000e+08,9.000000e+07

In [102]:
# Using shape to get the dimensions of the DataFrame
transfers.shape

(40208, 10)

In [103]:
# Using columns to get the columns of the DataFrame
transfers.columns

Index(['player_id', 'transfer_date', 'transfer_season', 'from_club_id',
       'to_club_id', 'from_club_name', 'to_club_name', 'transfer_fee',
       'market_value_in_eur', 'player_name'],
      dtype='object')

In [104]:
# Using dtypes to get the data types of the DataFrame
transfers.dtypes

player_id                int64
transfer_date           object
transfer_season         object
from_club_id             int64
to_club_id               int64
from_club_name          object
to_club_name            object
transfer_fee           float64
market_value_in_eur    float64
player_name             object
dtype: object

# Stage 1.3 Cleaning

In [105]:
# Using dropna() to remove any rows with null values
transfers_no_nulls = transfers.dropna()
transfers_no_nulls.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19647 entries, 0 to 39892
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            19647 non-null  int64
 1   transfer_date        19647 non-null  object
 2   transfer_season      19647 non-null  object
 3   from_club_id         19647 non-null  int64
 4   to_club_id           19647 non-null  int64
 5   from_club_name       19647 non-null  object
 6   to_club_name         19647 non-null  object
 7   transfer_fee         19647 non-null  float64
 8   market_value_in_eur  19647 non-null  float64
 9   player_name          19647 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 1.6+ MB

In [106]:
# Using fillna() to fill in any null values with a value
transfers['transfer_fee'] = transfers['transfer_fee'].fillna(0)
transfers['market_value_in_eur'] = transfers['market_value_in_eur'].fillna(0)
transfers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40208 entries, 0 to 40207
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            40208 non-null  int64
 1   transfer_date        40208 non-null  object
 2   transfer_season      40208 non-null  object
 3   from_club_id         40208 non-null  int64
 4   to_club_id           40208 non-null  int64
 5   from_club_name       40208 non-null  object
 6   to_club_name         40208 non-null  object
 7   transfer_fee         40208 non-null  float64
 8   market_value_in_eur  40208 non-null  float64
 9   player_name          40208 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 3.1+ MB

In [107]:
# Using astype() to change data type of a column
transfers['player_id'] = transfers['player_id'].astype('str')
transfers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40208 entries, 0 to 40207
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            40208 non-null  object
 1   transfer_date        40208 non-null  object
 2   transfer_season      40208 non-null  object
 3   from_club_id         40208 non-null  int64
 4   to_club_id           40208 non-null  int64
 5   from_club_name       40208 non-null  object
 6   to_club_name         40208 non-null  object
 7   transfer_fee         40208 non-null  float64
 8   market_value_in_eur  40208 non-null  float64
 9   player_name          40208 non-null  object
dtypes: float64(2), int64(2), object(6)
memory usage: 3.1+ MB

In [108]:
# Using drop_duplicates() to remove any duplicates and get unqiue values
buying_club = transfers['to_club_name']
buying_club_unique = buying_club.drop_duplicates().reset_index()
buying_club_unique

      index     to_club_name
0         0        FC Empoli
1         1      Antalyaspor
2         2      Santa Clara
3         3    Atlético-MG B
4         4   Fakel Voronezh
...     ...              ...
6118  40195  FC Alsbach Jgd.
6119  40202  B. Velbert Yth.
6120  40203    Habingh. Yth.
6121  40206   Sorrento Youth
6122  40207  VfR Rauxel Yth.

[6123 rows x 2 columns]

In [109]:
#Dropping duplicated rows
transfers = transfers.drop_duplicates()
transfers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40208 entries, 0 to 40207
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            40208 non-null  object
 1   transfer_date        40208 non-null  object
 2   transfer_season      40208 non-null  object
 3   from_club_id         40208 non-null  int64
 4   to_club_id           40208 non-null  int64
 5   from_club_name       40208 non-null  object
 6   to_club_name         40208 non-null  object
 7   transfer_fee         40208 non-null  float64
 8   market_value_in_eur  40208 non-null  float64
 9   player_name          40208 non-null  object
dtypes: float64(2), int64(2), object(6)
memory usage: 3.1+ MB

In [110]:
#Getting latest transfer for each player
transfers = transfers.sort_values('transfer_date', ascending = False)
transfers_unique_players = transfers.drop_duplicates(subset = 'player_id')
transfers_unique_players.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5079 entries, 0 to 38185
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            5079 non-null   object
 1   transfer_date        5079 non-null   object
 2   transfer_season      5079 non-null   object
 3   from_club_id         5079 non-null   int64
 4   to_club_id           5079 non-null   int64
 5   from_club_name       5079 non-null   object
 6   to_club_name         5079 non-null   object
 7   transfer_fee         5079 non-null   float64
 8   market_value_in_eur  5079 non-null   float64
 9   player_name          5079 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 436.5+ KB

In [111]:
#Using rename() to rename columns
transfers_updated = transfers.rename({'from_club_name': 'selling_club','to_club_name': 'buying_clubs'}, axis=1)
transfers_updated.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40208 entries, 0 to 40207
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            40208 non-null  object
 1   transfer_date        40208 non-null  object
 2   transfer_season      40208 non-null  object
 3   from_club_id         40208 non-null  int64
 4   to_club_id           40208 non-null  int64
 5   selling_club         40208 non-null  object
 6   buying_clubs         40208 non-null  object
 7   transfer_fee         40208 non-null  float64
 8   market_value_in_eur  40208 non-null  float64
 9   player_name          40208 non-null  object
dtypes: float64(2), int64(2), object(6)
memory usage: 3.4+ MB

In [112]:
transfers_updated['Transfer_type'] = "Free Agent"
transfers_updated.loc[(transfers_updated['transfer_fee'] == 0) & (transfers_updated['market_value_in_eur'] == 0),'Transfer_type'] = 'Free Agent'
transfers_updated.loc[(transfers_updated['transfer_fee'] == 0) & (transfers_updated['market_value_in_eur'] != 0),'Transfer_type'] = 'Free Transfer'
transfers_updated.loc[(transfers_updated['transfer_fee'] != 0), 'Transfer_type'] = 'Paid Transfer'
transfers_updated['Transfer_type'] = pd.Categorical(transfers_updated['Transfer_type'], ['Free Agent','Free Transfer','Paid Transfer'])
transfers_updated.dtypes

player_id                object
transfer_date            object
transfer_season          object
from_club_id              int64
to_club_id                int64
selling_club             object
buying_clubs             object
transfer_fee            float64
market_value_in_eur     float64
player_name              object
Transfer_type          category
dtype: object

# Stage 1.4 Row Navigation

In [113]:
# Using .shift() to get the previous year/month/day value

transfers_for_clubs =  transfers_updated[['transfer_date','buying_clubs','transfer_fee']]
transfers_for_clubs['transfer_date'] = pd.to_datetime(transfers_for_clubs['transfer_date'])
transfers_for_clubs['Year'] = transfers_for_clubs['transfer_date'].dt.year
transfers_manc = transfers_for_clubs[transfers_for_clubs['buying_clubs'] == 'Man City']
transfers_manc = transfers_manc.groupby('Year', as_index = False).agg({'transfer_fee':'sum'}).sort_values('Year',ascending = True)
transfers_manc['Previouzs_year_transfer_fee'] = transfers_manc['transfer_fee'].shift(1)
transfers_manc.head()

/var/folders/40/y5y_nm9x38z4vm7dvygk85tw0000gn/T/ipykernel_71991/3317671507.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transfers_for_clubs['transfer_date'] = pd.to_datetime(transfers_for_clubs['transfer_date'])
/var/folders/40/y5y_nm9x38z4vm7dvygk85tw0000gn/T/ipykernel_71991/3317671507.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transfers_for_clubs['Year'] = transfers_for_clubs['transfer_date'].dt.year

   Year  transfer_fee  Previouzs_year_transfer_fee
0  2006      900000.0                          NaN
1  2007           0.0                     900000.0
2  2010    42000000.0                          0.0
3  2011           0.0                   42000000.0
4  2012    15200000.0                          0.0

In [114]:
# Using .diff() to get the yearly/monthly/daily difference
transfers_manc['YoY_difference'] = transfers_manc['transfer_fee'].diff()
transfers_manc.head()

   Year  transfer_fee  Previouzs_year_transfer_fee  YoY_difference
0  2006      900000.0                          NaN             NaN
1  2007           0.0                     900000.0       -900000.0
2  2010    42000000.0                          0.0      42000000.0
3  2011           0.0                   42000000.0     -42000000.0
4  2012    15200000.0                          0.0      15200000.0

# Stage 1.5 NumPy basics

In [121]:
# NumPy array transfer conversion
transfer_market = np.array(transfers_updated[['transfer_fee','market_value_in_eur']])
transfer_market

array([[     0., 700000.],
       [     0.,      0.],
       [     0., 100000.],
       ...,
       [     0.,      0.],
       [     0.,      0.],
       [     0.,      0.]], shape=(40208, 2))

In [134]:
# Reshape Numpy array
numpy_transfer_fee = transfer_market[:,0]
numpy_transfer_fee_reshape = numpy_transfer_fee.reshape(2513,16)
numpy_transfer_fee_reshape

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(2513, 16))

In [137]:
# Vectorization example, convesion of currency using scalar transformation
numpy_transfer_fee_eur = numpy_transfer_fee
numpy_transfer_fee_GBP = numpy_transfer_fee*0.8618

print(numpy_transfer_fee_eur.mean())
print(numpy_transfer_fee_GBP.mean())

243830.01034619976
210132.70291635496

In [144]:
# Vectorization example, substracting two arrays
numpy_transfer_fee_eur
numpy_market_value = transfer_market[:,1]
Transfer_diff = numpy_transfer_fee_eur - numpy_market_value
print(Transfer_diff.mean())

-508437.9711500199