In [155]:
import pandas as pd
import numpy as np

In [156]:
#Import csv
file_path_transfers = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/transfers.csv"
transfers = pd.read_csv(file_path_transfers)

In [157]:
#Import csv
file_path_transfers = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/games.csv"
games = pd.read_csv(file_path_transfers)

In [158]:
file_path_transfers = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/appearances.csv"
appearances = pd.read_csv(file_path_transfers)

# Stage 2.1 Selection & filtering

In [159]:
# Select specific row using loc[]
games.loc[0:10]

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,...,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,...,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,...,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,...,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition
5,1027049,FIWC,2009,Round of 16,2010-06-29,3581,3435,5,3,NaN,...,Loftus Versfeld Stadium,36742.0,Frank De Bleeckere,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Paraguay,Japan,5:3,national_team_competition
6,1027635,FIWC,2009,Round of 16,2010-06-28,3439,3700,3,0,NaN,...,Ellis Park Stadium,54096.0,Howard Webb,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Brazil,Chile,3:0,national_team_competition
7,1027636,FIWC,2009,Round of 16,2010-06-29,3375,3300,1,0,NaN,...,Cape Town Stadium,62955.0,Héctor Baldassi,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Spain,Portugal,1:0,national_team_competition
8,1027723,FIWC,2009,Quarter-Finals,2010-07-02,3449,3441,5,3,NaN,...,FNB-Stadium,84000.0,Olegário Benquerença,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,Ghana,5:3,national_team_competition
9,1027750,FIWC,2009,Quarter-Finals,2010-07-03,3437,3262,0,4,NaN,...,Cape Town Stadium,64100.0,Ravshan Irmatov,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Germany,0:4,national_team_competition
10,1028533,FIWC,2009,Quarter-Finals,2010-07-02,3379,3439,2,1,NaN,...,Nelson Mandela Bay Stadium,40186.0,Yuichi Nishimura,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Brazil,2:1,national_team_competition

In [160]:
# Select specific row using iloc[]
games.iloc[0:10]

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,...,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,...,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,...,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,...,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition
5,1027049,FIWC,2009,Round of 16,2010-06-29,3581,3435,5,3,NaN,...,Loftus Versfeld Stadium,36742.0,Frank De Bleeckere,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Paraguay,Japan,5:3,national_team_competition
6,1027635,FIWC,2009,Round of 16,2010-06-28,3439,3700,3,0,NaN,...,Ellis Park Stadium,54096.0,Howard Webb,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Brazil,Chile,3:0,national_team_competition
7,1027636,FIWC,2009,Round of 16,2010-06-29,3375,3300,1,0,NaN,...,Cape Town Stadium,62955.0,Héctor Baldassi,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Spain,Portugal,1:0,national_team_competition
8,1027723,FIWC,2009,Quarter-Finals,2010-07-02,3449,3441,5,3,NaN,...,FNB-Stadium,84000.0,Olegário Benquerença,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,Ghana,5:3,national_team_competition
9,1027750,FIWC,2009,Quarter-Finals,2010-07-03,3437,3262,0,4,NaN,...,Cape Town Stadium,64100.0,Ravshan Irmatov,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Germany,0:4,national_team_competition

In [161]:
# Select specific rows using boolean masks
England_games = games[(games['home_club_name'] == 'England') | (games['away_club_name'] == 'England')]
England_games.head(5)

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
37,1169010,EURO,2011,Group D,2012-06-11,3377,3299,1,1,NaN,...,Donbass Arena,47400.0,Nicola Rizzoli,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,France,England,1:1,national_team_competition
39,1169012,EURO,2011,Group D,2012-06-15,3557,3299,2,3,NaN,...,NSK Olimpisky,64640.0,Damir Skomina,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Sweden,England,2:3,national_team_competition
42,1169015,EURO,2011,Group D,2012-06-19,3299,3699,1,0,NaN,...,Donbass Arena,48000.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,England,Ukraine,1:0,national_team_competition
48,2219616,EURO,2011,Quarter-Finals,2012-06-24,3299,3376,2,4,NaN,...,NSK Olimpisky,64340.0,Pedro Proença,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,England,Italy,2:4,national_team_competition

# Stage 2.2 Group By & Aggregation

In [162]:
def result(x,y):
    if x > y:
        return 'Home Win'
    elif x == y:
        return 'Draw'
    elif x < y:
        return 'Away Win'
    else:
        return None

In [163]:
def win_draw_loss(x,y):
    if x == 'Draw':
        return 'D'
    elif (x == 'Home Win' and y == 'Home'):
        return 'W'
    elif (x == 'Away Win' and y == 'Away'):
        return 'W'
    elif (x == 'Home Win' and y == 'Away'):
        return 'L'
    elif (x == 'Away Win' and y == 'Home'):
        return 'L'
    else:
        return None

In [164]:
def point(x):
    if x == 'W':
        return 3
    elif x == 'D':
        return 1
    elif x == 'L':
        return 0
    else:
        return None

In [165]:
games['Result'] = games[['home_club_goals','away_club_goals']].apply(
    lambda row: result(row['home_club_goals'], row['away_club_goals']),
    axis=1
)

home_games = games[['game_id','competition_id','season','round','home_club_id','home_club_goals','stadium','attendance','referee','home_club_name','competition_type','Result']].rename({'home_club_id':'club_id','home_club_goals':'goals','home_club_name':'club_name'},axis=1)
away_games = games[['game_id','competition_id','season','round','away_club_id','away_club_goals','stadium','attendance','referee','away_club_name','competition_type','Result']].rename({'away_club_id':'club_id','away_club_goals':'goals','away_club_name':'club_name'},axis=1)
home_games['Location'] = 'Home'
away_games['Location'] = 'Away'
all_games = pd.concat([home_games, away_games])
all_games['result'] = all_games[['Result','Location']].apply(
    lambda row: win_draw_loss(row['Result'], row['Location']),
    axis=1
)
all_games

,game_id,competition_id,season,round,club_id,goals,stadium,attendance,referee,club_name,competition_type,Result,Location,result
0,1026846,FIWC,2009,Round of 16,3449,2,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,Uruguay,national_team_competition,Home Win,Home,W
1,1026847,FIWC,2009,Round of 16,3437,3,FNB-Stadium,84377.0,Roberto Rosetti,Argentina,national_team_competition,Home Win,Home,W
2,1027001,FIWC,2009,Round of 16,3505,1,Royal Bafokeng Stadium,34976.0,Viktor Kassai,United States,national_team_competition,Away Win,Home,L
3,1027002,FIWC,2009,Round of 16,3262,4,Free State Stadium,40510.0,Jorge Larrionda,Germany,national_team_competition,Home Win,Home,W
4,1027048,FIWC,2009,Round of 16,3379,2,Moses Mabhida Stadion,61962.0,Undiano Mallenco,Netherlands,national_team_competition,Home Win,Home,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88803,986818,FIWC,2009,Group F,9171,0,Peter Mokaba Stadion,34850.0,Yuichi Nishimura,New Zealand,national_team_competition,Draw,Away,D
88804,986819,FIWC,2009,Group G,3439,0,Moses Mabhida Stadion,62712.0,Armando Archundia Téllez,Brazil,national_team_competition,Draw,Away,D
88805,986820,FIWC,2009,Group G,3591,3,Mbombela Stadium,34763.0,Undiano Mallenco,Ivory Coast,national_team_competition,Away Win,Away,W
88806,986821,FIWC,2009,Group H,3375,2,Loftus Versfeld Stadium,41958.0,Marco Rodríguez,Spain,national_team_competition,Away Win,Away,W
88807,986822,FIWC,2009,Group H,3590,0,Free State Stadium,28042.0,Héctor Baldassi,Honduras,national_team_competition,Draw,Away,D

In [166]:
# Using GroupBy and agg
Club_results = all_games.groupby('club_name').agg({'game_id':'count','goals':'mean'}).reset_index()
Club_results
#Club_results[Club_results['club_name'] == 'England']

                                 club_name  game_id     goals
0                              Aarhus 1900        1  0.000000
1                 1. FC Lokomotive Leipzig        3  0.000000
2                           1. FC Slovácko       72  0.916667
3     1. Fußball- und Sportverein Mainz 05      528  1.407197
4                     1. Fußball-Club Köln      390  1.410256
...                                    ...      ...       ...
3161                             Újpest FC        8  1.500000
3162                          Ümraniyespor       36  1.305556
3163     İstanbul Başakşehir Futbol Kulübü      528  1.543561
3164                    Železničar Pančevo       60  1.316667
3165    Футбольный клуб "Локомотив" Москва      537  1.571695

[3166 rows x 3 columns]

In [167]:
# Using apply for rows
all_games['Points'] = all_games['result'].apply(point)
all_games.head(5)

,game_id,competition_id,season,round,club_id,goals,stadium,attendance,referee,club_name,competition_type,Result,Location,result,Points
0,1026846,FIWC,2009,Round of 16,3449,2,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,Uruguay,national_team_competition,Home Win,Home,W,3
1,1026847,FIWC,2009,Round of 16,3437,3,FNB-Stadium,84377.0,Roberto Rosetti,Argentina,national_team_competition,Home Win,Home,W,3
2,1027001,FIWC,2009,Round of 16,3505,1,Royal Bafokeng Stadium,34976.0,Viktor Kassai,United States,national_team_competition,Away Win,Home,L,0
3,1027002,FIWC,2009,Round of 16,3262,4,Free State Stadium,40510.0,Jorge Larrionda,Germany,national_team_competition,Home Win,Home,W,3
4,1027048,FIWC,2009,Round of 16,3379,2,Moses Mabhida Stadion,61962.0,Undiano Mallenco,Netherlands,national_team_competition,Home Win,Home,W,3

# Stage 2.3 Merging & joining

In [182]:
# Merge example
player_games = appearances.merge(all_games, left_on = ['game_id','player_club_id'],right_on = ['game_id','club_id'], how = 'left')
player_games.sort_values('game_id').head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id_x,yellow_cards,red_cards,...,goals_y,stadium,attendance,referee,club_name,competition_type,Result,Location,result,Points
3349,2211607_34784,2211607,34784,610,467,2012-08-05,Lasse Schöne,NLSC,0,0,...,2,Johan Cruijff ArenA,50000.0,Björn Kuipers,AFC Ajax Amsterdam,other,Home Win,Away,L,0
3343,2211607_167850,2211607,167850,383,199,2012-08-05,Memphis Depay,NLSC,0,0,...,4,Johan Cruijff ArenA,50000.0,Björn Kuipers,Eindhovense Voetbalvereniging Philips Sport Ve...,other,Home Win,Home,W,3
3342,2211607_16101,2211607,16101,383,114,2012-08-05,Atiba Hutchinson,NLSC,0,0,...,4,Johan Cruijff ArenA,50000.0,Björn Kuipers,Eindhovense Voetbalvereniging Philips Sport Ve...,other,Home Win,Home,W,3
3341,2211607_146258,2211607,146258,383,467,2012-08-05,Jetro Willems,NLSC,0,0,...,4,Johan Cruijff ArenA,50000.0,Björn Kuipers,Eindhovense Voetbalvereniging Philips Sport Ve...,other,Home Win,Home,W,3
3340,2211607_124891,2211607,124891,610,114,2012-08-05,Aras Özbiliz,NLSC,0,0,...,2,Johan Cruijff ArenA,50000.0,Björn Kuipers,AFC Ajax Amsterdam,other,Home Win,Away,L,0

In [ ]:
# Concat example
Season_2012 = player_games[player_games['season'] == 2012]
Season_2013 = player_games[player_games['season'] == 2013]
Season_2012_2013 = pd.concat([Season_2012,Season_2013], axis = 0, join = 'outer')
Season_2012_2013['season'].unique()

array([2012, 2013])