In [703]:
import pandas as pd
import numpy as np

In [704]:
#Import csv
file_path_transfers = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/transfers.csv"
transfers = pd.read_csv(file_path_transfers)

In [705]:
#Import csv
file_path_transfers = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/games.csv"
games = pd.read_csv(file_path_transfers)

In [706]:
file_path_transfers = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/Football Data from Transfermarkt/appearances.csv"
appearances = pd.read_csv(file_path_transfers)

# Stage 2.1 Selection & filtering

In [707]:
# Select specific row using loc[]
games.loc[0:10]

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,...,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,...,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,...,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,...,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition
5,1027049,FIWC,2009,Round of 16,2010-06-29,3581,3435,5,3,NaN,...,Loftus Versfeld Stadium,36742.0,Frank De Bleeckere,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Paraguay,Japan,5:3,national_team_competition
6,1027635,FIWC,2009,Round of 16,2010-06-28,3439,3700,3,0,NaN,...,Ellis Park Stadium,54096.0,Howard Webb,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Brazil,Chile,3:0,national_team_competition
7,1027636,FIWC,2009,Round of 16,2010-06-29,3375,3300,1,0,NaN,...,Cape Town Stadium,62955.0,Héctor Baldassi,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Spain,Portugal,1:0,national_team_competition
8,1027723,FIWC,2009,Quarter-Finals,2010-07-02,3449,3441,5,3,NaN,...,FNB-Stadium,84000.0,Olegário Benquerença,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,Ghana,5:3,national_team_competition
9,1027750,FIWC,2009,Quarter-Finals,2010-07-03,3437,3262,0,4,NaN,...,Cape Town Stadium,64100.0,Ravshan Irmatov,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Germany,0:4,national_team_competition
10,1028533,FIWC,2009,Quarter-Finals,2010-07-02,3379,3439,2,1,NaN,...,Nelson Mandela Bay Stadium,40186.0,Yuichi Nishimura,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Brazil,2:1,national_team_competition

In [708]:
# Select specific row using iloc[]
games.iloc[0:10]

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,...,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,...,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,...,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,...,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition
5,1027049,FIWC,2009,Round of 16,2010-06-29,3581,3435,5,3,NaN,...,Loftus Versfeld Stadium,36742.0,Frank De Bleeckere,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Paraguay,Japan,5:3,national_team_competition
6,1027635,FIWC,2009,Round of 16,2010-06-28,3439,3700,3,0,NaN,...,Ellis Park Stadium,54096.0,Howard Webb,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Brazil,Chile,3:0,national_team_competition
7,1027636,FIWC,2009,Round of 16,2010-06-29,3375,3300,1,0,NaN,...,Cape Town Stadium,62955.0,Héctor Baldassi,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Spain,Portugal,1:0,national_team_competition
8,1027723,FIWC,2009,Quarter-Finals,2010-07-02,3449,3441,5,3,NaN,...,FNB-Stadium,84000.0,Olegário Benquerença,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,Ghana,5:3,national_team_competition
9,1027750,FIWC,2009,Quarter-Finals,2010-07-03,3437,3262,0,4,NaN,...,Cape Town Stadium,64100.0,Ravshan Irmatov,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Germany,0:4,national_team_competition

In [709]:
# Select specific rows using boolean masks
England_games = games[(games['home_club_name'] == 'England') | (games['away_club_name'] == 'England')]
England_games.head(5)

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
37,1169010,EURO,2011,Group D,2012-06-11,3377,3299,1,1,NaN,...,Donbass Arena,47400.0,Nicola Rizzoli,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,France,England,1:1,national_team_competition
39,1169012,EURO,2011,Group D,2012-06-15,3557,3299,2,3,NaN,...,NSK Olimpisky,64640.0,Damir Skomina,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Sweden,England,2:3,national_team_competition
42,1169015,EURO,2011,Group D,2012-06-19,3299,3699,1,0,NaN,...,Donbass Arena,48000.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,England,Ukraine,1:0,national_team_competition
48,2219616,EURO,2011,Quarter-Finals,2012-06-24,3299,3376,2,4,NaN,...,NSK Olimpisky,64340.0,Pedro Proença,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,England,Italy,2:4,national_team_competition

# Stage 2.2 Group By & Aggregation

In [710]:
def result(x,y):
    if x > y:
        return 'Home Win'
    elif x == y:
        return 'Draw'
    elif x < y:
        return 'Away Win'
    else:
        return None

In [711]:
def win_draw_loss(x,y):
    if x == 'Draw':
        return 'D'
    elif (x == 'Home Win' and y == 'Home'):
        return 'W'
    elif (x == 'Away Win' and y == 'Away'):
        return 'W'
    elif (x == 'Home Win' and y == 'Away'):
        return 'L'
    elif (x == 'Away Win' and y == 'Home'):
        return 'L'
    else:
        return None

In [712]:
def point(x):
    if x == 'W':
        return 3
    elif x == 'D':
        return 1
    elif x == 'L':
        return 0
    else:
        return None

In [713]:
games['Result'] = games[['home_club_goals','away_club_goals']].apply(
    lambda row: result(row['home_club_goals'], row['away_club_goals']),
    axis=1
)

home_games = games[['game_id','date','competition_id','season','round','home_club_id','home_club_goals','stadium','attendance','referee','home_club_name','competition_type','Result']].rename({'home_club_id':'club_id','home_club_goals':'goals','home_club_name':'club_name'},axis=1)
away_games = games[['game_id','date','competition_id','season','round','away_club_id','away_club_goals','stadium','attendance','referee','away_club_name','competition_type','Result']].rename({'away_club_id':'club_id','away_club_goals':'goals','away_club_name':'club_name'},axis=1)
home_games['Location'] = 'Home'
away_games['Location'] = 'Away'
all_games = pd.concat([home_games, away_games])
all_games['result'] = all_games[['Result','Location']].apply(
    lambda row: win_draw_loss(row['Result'], row['Location']),
    axis=1
)
all_games

,game_id,date,competition_id,season,round,club_id,goals,stadium,attendance,referee,club_name,competition_type,Result,Location,result
0,1026846,2010-06-26,FIWC,2009,Round of 16,3449,2,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,Uruguay,national_team_competition,Home Win,Home,W
1,1026847,2010-06-27,FIWC,2009,Round of 16,3437,3,FNB-Stadium,84377.0,Roberto Rosetti,Argentina,national_team_competition,Home Win,Home,W
2,1027001,2010-06-26,FIWC,2009,Round of 16,3505,1,Royal Bafokeng Stadium,34976.0,Viktor Kassai,United States,national_team_competition,Away Win,Home,L
3,1027002,2010-06-27,FIWC,2009,Round of 16,3262,4,Free State Stadium,40510.0,Jorge Larrionda,Germany,national_team_competition,Home Win,Home,W
4,1027048,2010-06-28,FIWC,2009,Round of 16,3379,2,Moses Mabhida Stadion,61962.0,Undiano Mallenco,Netherlands,national_team_competition,Home Win,Home,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88803,986818,2010-06-24,FIWC,2009,Group F,9171,0,Peter Mokaba Stadion,34850.0,Yuichi Nishimura,New Zealand,national_team_competition,Draw,Away,D
88804,986819,2010-06-25,FIWC,2009,Group G,3439,0,Moses Mabhida Stadion,62712.0,Armando Archundia Téllez,Brazil,national_team_competition,Draw,Away,D
88805,986820,2010-06-25,FIWC,2009,Group G,3591,3,Mbombela Stadium,34763.0,Undiano Mallenco,Ivory Coast,national_team_competition,Away Win,Away,W
88806,986821,2010-06-25,FIWC,2009,Group H,3375,2,Loftus Versfeld Stadium,41958.0,Marco Rodríguez,Spain,national_team_competition,Away Win,Away,W
88807,986822,2010-06-25,FIWC,2009,Group H,3590,0,Free State Stadium,28042.0,Héctor Baldassi,Honduras,national_team_competition,Draw,Away,D

In [714]:
# Using GroupBy and agg
Club_results = all_games.groupby('club_name').agg({'game_id':'count','goals':'mean'}).reset_index()
Club_results
#Club_results[Club_results['club_name'] == 'England']

                                 club_name  game_id     goals
0                              Aarhus 1900        1  0.000000
1                 1. FC Lokomotive Leipzig        3  0.000000
2                           1. FC Slovácko       72  0.916667
3     1. Fußball- und Sportverein Mainz 05      528  1.407197
4                     1. Fußball-Club Köln      390  1.410256
...                                    ...      ...       ...
3161                             Újpest FC        8  1.500000
3162                          Ümraniyespor       36  1.305556
3163     İstanbul Başakşehir Futbol Kulübü      528  1.543561
3164                    Železničar Pančevo       60  1.316667
3165    Футбольный клуб "Локомотив" Москва      537  1.571695

[3166 rows x 3 columns]

In [715]:
# Using apply for rows
all_games['Points'] = all_games['result'].apply(point)
all_games.head(5)

,game_id,date,competition_id,season,round,club_id,goals,stadium,attendance,referee,club_name,competition_type,Result,Location,result,Points
0,1026846,2010-06-26,FIWC,2009,Round of 16,3449,2,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,Uruguay,national_team_competition,Home Win,Home,W,3
1,1026847,2010-06-27,FIWC,2009,Round of 16,3437,3,FNB-Stadium,84377.0,Roberto Rosetti,Argentina,national_team_competition,Home Win,Home,W,3
2,1027001,2010-06-26,FIWC,2009,Round of 16,3505,1,Royal Bafokeng Stadium,34976.0,Viktor Kassai,United States,national_team_competition,Away Win,Home,L,0
3,1027002,2010-06-27,FIWC,2009,Round of 16,3262,4,Free State Stadium,40510.0,Jorge Larrionda,Germany,national_team_competition,Home Win,Home,W,3
4,1027048,2010-06-28,FIWC,2009,Round of 16,3379,2,Moses Mabhida Stadion,61962.0,Undiano Mallenco,Netherlands,national_team_competition,Home Win,Home,W,3

# Stage 2.3 Merging & joining

In [716]:
# Merge example
player_games = appearances.merge(all_games, left_on = ['game_id','player_club_id'],right_on = ['game_id','club_id'], how = 'left')
player_games.sort_values('game_id').head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date_x,player_name,competition_id_x,yellow_cards,red_cards,...,goals_y,stadium,attendance,referee,club_name,competition_type,Result,Location,result,Points
3349,2211607_34784,2211607,34784,610,467,2012-08-05,Lasse Schöne,NLSC,0,0,...,2,Johan Cruijff ArenA,50000.0,Björn Kuipers,AFC Ajax Amsterdam,other,Home Win,Away,L,0
3343,2211607_167850,2211607,167850,383,199,2012-08-05,Memphis Depay,NLSC,0,0,...,4,Johan Cruijff ArenA,50000.0,Björn Kuipers,Eindhovense Voetbalvereniging Philips Sport Ve...,other,Home Win,Home,W,3
3342,2211607_16101,2211607,16101,383,114,2012-08-05,Atiba Hutchinson,NLSC,0,0,...,4,Johan Cruijff ArenA,50000.0,Björn Kuipers,Eindhovense Voetbalvereniging Philips Sport Ve...,other,Home Win,Home,W,3
3341,2211607_146258,2211607,146258,383,467,2012-08-05,Jetro Willems,NLSC,0,0,...,4,Johan Cruijff ArenA,50000.0,Björn Kuipers,Eindhovense Voetbalvereniging Philips Sport Ve...,other,Home Win,Home,W,3
3340,2211607_124891,2211607,124891,610,114,2012-08-05,Aras Özbiliz,NLSC,0,0,...,2,Johan Cruijff ArenA,50000.0,Björn Kuipers,AFC Ajax Amsterdam,other,Home Win,Away,L,0

In [717]:
# Concat example
Season_2012 = player_games[player_games['season'] == 2012]
Season_2013 = player_games[player_games['season'] == 2013]
Season_2012_2013 = pd.concat([Season_2012,Season_2013], axis = 0, join = 'outer')
Season_2012_2013['season'].unique()

array([2012, 2013])

# Stage 2.4 Reshaping

In [718]:
# Create pivot table
Pivot_table = pd.pivot_table(all_games, index = 'club_name', columns = 'result', values = 'Points', aggfunc = 'count').reset_index()
Pivot_table[Pivot_table['club_name'] == 'England']

result club_name     D     L     W
1014     England  11.0  12.0  23.0

In [719]:
# Create long format using melt
club_goals_form = pd.melt(all_games,id_vars =['club_name'], value_vars = ['goals','Points'], var_name = 'Stats', value_name = 'Value' )
club_goals_form.sort_values('club_name')

                       club_name   Stats  Value
66192                Aarhus 1900   goals      0
243808               Aarhus 1900  Points      0
53251   1. FC Lokomotive Leipzig   goals      0
63257   1. FC Lokomotive Leipzig   goals      0
240873  1. FC Lokomotive Leipzig  Points      0
...                          ...     ...    ...
353096                       NaN  Points      0
353097                       NaN  Points      0
353103                       NaN  Points      0
353109                       NaN  Points      0
353110                       NaN  Points      0

[355232 rows x 3 columns]

In [720]:
# Create long format using stack
all_games_stacked = all_games.set_index(['game_id','club_name']).stack()
all_games_stacked.head()

game_id  club_name
1026846  Uruguay    date               2010-06-26
                    competition_id           FIWC
                    season                   2009
                    round             Round of 16
                    club_id                  3449
dtype: object

In [721]:
# Unstack - convert from wide to long
all_games_un_stacked = all_games_stacked.unstack().reset_index()
all_games_un_stacked

,game_id,club_name,date,competition_id,season,round,club_id,goals,stadium,attendance,referee,competition_type,Result,Location,result,Points
0,25767,Costa Rica,2006-06-09,FIWC,2005,Group A,8497,2,Allianz Arena,66000.0,Horacio Elizondo,national_team_competition,Home Win,Away,L,0
1,25767,Germany,2006-06-09,FIWC,2005,Group A,3262,4,Allianz Arena,66000.0,Horacio Elizondo,national_team_competition,Home Win,Home,W,3
2,31198,Ecuador,2006-06-09,FIWC,2005,Group A,5750,2,Veltins-Arena,52000.0,Toru Kamikawa,national_team_competition,Away Win,Away,W,3
3,31198,Poland,2006-06-09,FIWC,2005,Group A,3442,0,Veltins-Arena,52000.0,Toru Kamikawa,national_team_competition,Away Win,Home,L,0
4,31199,England,2006-06-10,FIWC,2005,Group B,3299,1,Deutsche Bank Park,43324.0,Alain Georges,national_team_competition,Home Win,Home,W,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177611,4869248,Società Sportiva Lazio S.p.A.,2026-05-13,CIT,2025,Final,398,0,Olimpico di Roma,68729.0,Marco Guida,domestic_cup,Away Win,Home,L,0
177612,4872130,Chelsea Football Club,2026-05-16,FAC,2025,Final,631,0,Wembley Stadium,83337.0,Darren England,domestic_cup,Away Win,Home,L,0
177613,4872130,Manchester City Football Club,2026-05-16,FAC,2025,Final,281,1,Wembley Stadium,83337.0,Darren England,domestic_cup,Away Win,Away,W,3
177614,4882370,FK Krasnodar,2026-05-24,RUP,2025,Final,16704,4,Luzhniki Stadium,72978.0,Inal Tanashev,domestic_cup,Home Win,Away,L,0
177615,4882370,FK Spartak Moskva,2026-05-24,RUP,2025,Final,232,5,Luzhniki Stadium,72978.0,Inal Tanashev,domestic_cup,Home Win,Home,W,3

# Stage 2.5 Datetime handling

In [722]:
# Converting to date data type

all_games['date'] = pd.to_datetime(all_games['date'])
all_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 177616 entries, 0 to 88807
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   game_id           177616 non-null  int64
 1   date              177616 non-null  datetime64[ns]
 2   competition_id    177616 non-null  object
 3   season            177616 non-null  int64
 4   round             177616 non-null  object
 5   club_id           177616 non-null  int64
 6   goals             177616 non-null  int64
 7   stadium           177132 non-null  object
 8   attendance        156000 non-null  float64
 9   referee           176260 non-null  object
 10  club_name         177494 non-null  object
 11  competition_type  177616 non-null  object
 12  Result            177616 non-null  object
 13  Location          177616 non-null  object
 14  result            177616 non-null  object
 15  Points            177616 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(9)
memory usage: 23.0+ MB

In [723]:
# get year, month, dayofweek, day name
all_games['Year'] = all_games['date'].dt.year
all_games['Month'] = all_games['date'].dt.month
all_games['Week_num'] = all_games['date'].dt.dayofweek
all_games['Day'] = all_games['date'].dt.day_name()
all_games.head()

,game_id,date,competition_id,season,round,club_id,goals,stadium,attendance,referee,club_name,competition_type,Result,Location,result,Points,Year,Month,Week_num,Day
0,1026846,2010-06-26,FIWC,2009,Round of 16,3449,2,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,Uruguay,national_team_competition,Home Win,Home,W,3,2010,6,5,Saturday
1,1026847,2010-06-27,FIWC,2009,Round of 16,3437,3,FNB-Stadium,84377.0,Roberto Rosetti,Argentina,national_team_competition,Home Win,Home,W,3,2010,6,6,Sunday
2,1027001,2010-06-26,FIWC,2009,Round of 16,3505,1,Royal Bafokeng Stadium,34976.0,Viktor Kassai,United States,national_team_competition,Away Win,Home,L,0,2010,6,5,Saturday
3,1027002,2010-06-27,FIWC,2009,Round of 16,3262,4,Free State Stadium,40510.0,Jorge Larrionda,Germany,national_team_competition,Home Win,Home,W,3,2010,6,6,Sunday
4,1027048,2010-06-28,FIWC,2009,Round of 16,3379,2,Moses Mabhida Stadion,61962.0,Undiano Mallenco,Netherlands,national_team_competition,Home Win,Home,W,3,2010,6,0,Monday

# Stage 2.6 Time-Intelligence functions

In [724]:
file_path_sales = "/Users/munavwarhussain/Library/Mobile Documents/com~apple~CloudDocs/Career Work/Job Preperation/Technical Tools & Roles/Python/Python Data Analyst Skill Check/Data/sales.csv"
sales = pd.read_csv(file_path_sales)
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21912 entries, 0 to 21911
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           21912 non-null  object
 1   store_id       21912 non-null  int64
 2   category_id    21912 non-null  int64
 3   sales_qty      21912 non-null  int64
 4   sales_revenue  21912 non-null  float64
dtypes: float64(1), int64(3), object(1)
memory usage: 856.1+ KB

In [725]:
# Creating date range
dates = pd.date_range(start = sales['date'].min(), end = sales['date'].max(), freq = 'D')
dates

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10',
               ...
               '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25',
               '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29',
               '2022-12-30', '2022-12-31'],
              dtype='datetime64[ns]', length=1826, freq='D')

In [726]:
# Changing time series data to change frequency 
sales['date'] = pd.to_datetime(sales['date'])
sales_resampled_month = sales.resample('M', on = 'date').sum()[['sales_qty','sales_revenue']].reset_index()
print(sales_resampled_month.head())
sales_resampled_year = sales.resample('Y', on = 'date').sum()[['sales_qty','sales_revenue']].reset_index()
print(sales_resampled_year.head())

        date  sales_qty  sales_revenue
0 2018-01-31      35088      219005.86
1 2018-02-28      31288      186128.05
2 2018-03-31      35785      205490.98
3 2018-04-30      38396      235117.02
4 2018-05-31      42312      252099.23
        date  sales_qty  sales_revenue
0 2018-12-31     498738     2992644.64
1 2019-12-31     511609     3070215.52
2 2020-12-31     522271     3126951.49
3 2021-12-31     531172     3169754.94
4 2022-12-31     541386     3249449.33

/var/folders/40/y5y_nm9x38z4vm7dvygk85tw0000gn/T/ipykernel_99796/1608663186.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  sales_resampled_month = sales.resample('M', on = 'date').sum()[['sales_qty','sales_revenue']].reset_index()
/var/folders/40/y5y_nm9x38z4vm7dvygk85tw0000gn/T/ipykernel_99796/1608663186.py:5: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  sales_resampled_year = sales.resample('Y', on = 'date').sum()[['sales_qty','sales_revenue']].reset_index()

In [727]:
# Making a date column an index
sales = sales.set_index(sales['date'])
sales.head()

                 date  store_id  category_id  sales_qty  sales_revenue
date
2018-01-01 2018-01-01         1            1         42         317.70
2018-01-02 2018-01-02         1            1         50         467.30
2018-01-03 2018-01-03         1            1         44         132.19
2018-01-04 2018-01-04         1            1         57         249.61
2018-01-05 2018-01-05         1            1         52         422.56

In [728]:
# Find Previous months value, MoM difference and percentage change
sales_resampled_month['Year-Month'] = sales_resampled_month['date'].dt.strftime('%Y-%m')
sales_resampled_month['Previous_Month_Revenue'] = sales_resampled_month['sales_revenue'].shift(1)
sales_resampled_month['MoM_difference'] = sales_resampled_month['sales_revenue'].diff(1)
sales_resampled_month['MoM_pct_change'] = sales_resampled_month['sales_revenue'].pct_change(1)*100
sales_resampled_month.head()

,date,sales_qty,sales_revenue,Year-Month,Previous_Month_Revenue,MoM_difference,MoM_pct_change
0,2018-01-31,35088,219005.86,2018-01,NaN,NaN,NaN
1,2018-02-28,31288,186128.05,2018-02,219005.86,-32877.81,-15.012297
2,2018-03-31,35785,205490.98,2018-03,186128.05,19362.93,10.403016
3,2018-04-30,38396,235117.02,2018-04,205490.98,29626.04,14.417197
4,2018-05-31,42312,252099.23,2018-05,235117.02,16982.21,7.222876

In [729]:
# Upsampling to get sales for every day
sales_resampled_month = sales_resampled_month[['sales_qty','sales_revenue','Year-Month']]
sales_resampled_month['Year-Month'] = pd.to_datetime(sales_resampled_month['Year-Month'])
sales_resampled_month = sales_resampled_month.set_index('Year-Month')
sales_resampled_day = sales_resampled_month.asfreq('D', method=None)
sales_resampled_day

            sales_qty  sales_revenue
Year-Month
2018-01-01    35088.0      219005.86
2018-01-02        NaN            NaN
2018-01-03        NaN            NaN
2018-01-04        NaN            NaN
2018-01-05        NaN            NaN
...               ...            ...
2022-11-27        NaN            NaN
2022-11-28        NaN            NaN
2022-11-29        NaN            NaN
2022-11-30        NaN            NaN
2022-12-01    43234.0      257231.66

[1796 rows x 2 columns]

In [730]:
# Front fill
sales_resampled_day_ffill = sales_resampled_day.ffill()
sales_resampled_day_ffill.head(13)

            sales_qty  sales_revenue
Year-Month
2018-01-01    35088.0      219005.86
2018-01-02    35088.0      219005.86
2018-01-03    35088.0      219005.86
2018-01-04    35088.0      219005.86
2018-01-05    35088.0      219005.86
2018-01-06    35088.0      219005.86
2018-01-07    35088.0      219005.86
2018-01-08    35088.0      219005.86
2018-01-09    35088.0      219005.86
2018-01-10    35088.0      219005.86
2018-01-11    35088.0      219005.86
2018-01-12    35088.0      219005.86
2018-01-13    35088.0      219005.86

In [731]:
#Interpolate
sales_resampled_day_interpolate = sales_resampled_day.interpolate()
sales_resampled_day_interpolate.head(13)

               sales_qty  sales_revenue
Year-Month
2018-01-01  35088.000000  219005.860000
2018-01-02  34965.419355  217945.285484
2018-01-03  34842.838710  216884.710968
2018-01-04  34720.258065  215824.136452
2018-01-05  34597.677419  214763.561935
2018-01-06  34475.096774  213702.987419
2018-01-07  34352.516129  212642.412903
2018-01-08  34229.935484  211581.838387
2018-01-09  34107.354839  210521.263871
2018-01-10  33984.774194  209460.689355
2018-01-11  33862.193548  208400.114839
2018-01-12  33739.612903  207339.540323
2018-01-13  33617.032258  206278.965806

In [732]:
# Cumulative sum and Cumulative product
sales_resampled_month['Cumulative sales'] = sales_resampled_month['sales_revenue'].cumsum()
sales_resampled_month['perc_change'] = sales_resampled_month['sales_revenue'].pct_change(1)
sales_resampled_month['perc_change'] = sales_resampled_month['perc_change'] + 1
sales_resampled_month['Growth_factor'] = sales_resampled_month['perc_change'].cumprod()
sales_resampled_month.head()

,sales_qty,sales_revenue,Cumulative sales,perc_change,Growth_factor
Year-Month,,,,,
2018-01-01,35088,219005.86,219005.86,NaN,NaN
2018-02-01,31288,186128.05,405133.91,0.849877,0.849877
2018-03-01,35785,205490.98,610624.89,1.104030,0.938290
2018-04-01,38396,235117.02,845741.91,1.144172,1.073565
2018-05-01,42312,252099.23,1097841.14,1.072229,1.151107

# Stage 2.7 String manipulation

In [733]:
# Upper and lower
transfers['player_upper'] = transfers['player_name'].str.upper()
transfers['player_lower'] = transfers['player_name'].str.lower()
transfers.head()

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name,player_upper,player_lower
0,467994,2030-06-30,25/26,5621,749,Reggiana,FC Empoli,0.0,700000.0,Luca Belardinelli,LUCA BELARDINELLI,luca belardinelli
1,739277,2027-05-30,26/27,42055,589,Genclik Gücü,Antalyaspor,0.0,NaN,Yannick Nkurunziza,YANNICK NKURUNZIZA,yannick nkurunziza
2,401533,2026-12-31,26/27,2029,2423,Ceará SC,Santa Clara,0.0,1500000.0,Matheusinho,MATHEUSINHO,matheusinho
3,468256,2026-12-31,26/27,2035,16655,Avaí FC,Atlético-MG B,0.0,700000.0,Daniel Penha,DANIEL PENHA,daniel penha
4,541914,2026-12-31,26/27,713,1124,BATE Borisov,Fakel Voronezh,0.0,225000.0,Anton Kovalev,ANTON KOVALEV,anton kovalev

In [734]:
# Using .str.contains to check that a patterns or string exists
transfers['transfer_date'].str.contains('^\d{4}-\d{2}-\d{2}$',regex=True).value_counts()

transfer_date
True    40208
Name: count, dtype: int64

In [735]:
# Using .str.startswith to check that string starst with. Only get 2000s date
transfers['transfer_date'].str.startswith('2').value_counts()

transfer_date
True     40177
False       31
Name: count, dtype: int64

In [736]:
# Using .str.endswith to check that string starst with. Only get 2000s date
CR7_apps = appearances[appearances['player_name'].str.endswith('Cristiano Ronaldo').fillna(False)]
CR7_apps.head()

/var/folders/40/y5y_nm9x38z4vm7dvygk85tw0000gn/T/ipykernel_99796/3048446162.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  CR7_apps = appearances[appearances['player_name'].str.endswith('Cristiano Ronaldo').fillna(False)]

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
8238,2244382_8198,2244382,8198,418,18544,2012-08-19,Cristiano Ronaldo,ES1,0,0,0,0,90
8948,2244388_8198,2244388,8198,418,18544,2012-08-22,Cristiano Ronaldo,SUC,0,0,1,0,90
11986,2242834_8198,2242834,8198,418,18544,2012-08-26,Cristiano Ronaldo,ES1,0,0,0,0,90
12902,2244389_8198,2244389,8198,418,18544,2012-08-29,Cristiano Ronaldo,SUC,0,0,1,0,90
16015,2242882_8198,2242882,8198,418,18544,2012-09-02,Cristiano Ronaldo,ES1,0,0,2,0,63

In [737]:
# Extract substrings (one position only
date = appearances['date'].str.extract(r'(\d+)',expand=True)
date.head()

      0
0  2012
1  2012
2  2012
3  2012
4  2012

In [738]:
#Extract all substrings
date = appearances['date'].str.extractall(r'(\d+)')
date.head()

            0
  match
0 0      2012
  1        07
  2        03
1 0      2012
  1        07

In [739]:
#Replace string or patterns for data cleaning
date = appearances['date'].str.replace('/','-')
date.head()

0    2012-07-03
1    2012-07-05
2    2012-07-05
3    2012-07-05
4    2012-07-05
Name: date, dtype: object

In [740]:
# Getting the index of a substring (first position)
index = appearances['player_name'].str.find(' ', start=0)
index.head()

0    8.0
1    6.0
2    6.0
3    5.0
4    6.0
Name: player_name, dtype: float64

In [741]:
# Splitting a column by a delimier
date_split = appearances['date'].str.split('-',expand=True)
date_split.head()

      0   1   2
0  2012  07  03
1  2012  07  05
2  2012  07  05
3  2012  07  05
4  2012  07  05

In [742]:
# Clean data by removing tailing spaces
appearances['player_name'] = appearances['player_name'].str.strip('')
appearances.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,76,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

# Stage 2.8 Advanced pandas

In [757]:
# Using applymap to transform every cell
all_games.applymap(lambda x: x.strip() if isinstance(x,str) else x)
all_games.head(2)
len(all_games)

/var/folders/40/y5y_nm9x38z4vm7dvygk85tw0000gn/T/ipykernel_99796/1393287817.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  all_games.applymap(lambda x: x.strip() if isinstance(x,str) else x)

177616

In [768]:
# Using transform with pivot table
grouped = all_games.groupby('season')['goals'].transform('sum')
grouped

177616

In [784]:
# Create multi-indexing
grouped = all_games.groupby(['club_id','season']).agg({'goals':'sum','Points':'sum'})
print(grouped.loc[(10,2025)])
print(grouped.xs(10,level='club_id'))

goals     2
Points    3
Name: (10, 2025), dtype: int64
        goals  Points
season
2012        5       3
2013        2       3
2014       17      12
2015        0       0
2016       14       9
2017        1       0
2018        5       3
2019        3       3
2020       26      35
2021       35      31
2022        7       3
2023       10       3
2024       13      15
2025        2       3

# Stage 2.9 Regex mastery

In [745]:
# Use re.compile to create regex match object
import re 
regex_match = re.compile(r'[\d]{4}-[\d]{2}-[\d]{2}')

In [746]:
# Use re.search() to create a match object and either produce the match or test the match
transfers['Date_check'] = transfers['transfer_date'].apply(lambda x: bool(re.search(regex_match,x)))
transfers['Actual_date'] = transfers['transfer_date'].apply(lambda x: re.search(regex_match,x).group())
print(transfers['Date_check'].value_counts())
transfers['Actual_date'].head(2)

Date_check
True    40208
Name: count, dtype: int64

0    2030-06-30
1    2027-05-30
Name: Actual_date, dtype: object

In [747]:
# Use re.match() to create a match object with the start of the string
transfers['Year'] = transfers['transfer_date'].apply(lambda x: re.search(r'\d{4}',x).group())
transfers['Year'].head(2)

0    2030
1    2027
Name: Year, dtype: object

In [748]:
# Use re.fullmatch() to create a match object that must match the exact string
transfers['Date_check'] = transfers['transfer_date'].apply(lambda x: re.fullmatch(r'\d{4}-\d{2}-\d{2}',x).group())
transfers['Date_check'].head(2)

0    2030-06-30
1    2027-05-30
Name: Date_check, dtype: object

In [749]:
# Use re.findall() to create a list of the multple matches of the string
split_date = transfers['transfer_date'].apply(lambda x: re.findall(r'[\d]+',x))
transfers['Year'] = split_date.apply(lambda x: x[0])
transfers['Month'] = split_date.apply(lambda x: x[1])
transfers['Day'] = split_date.apply(lambda x: x[2])

print(transfers['Year'].head(2))
print(transfers['Month'].head(2))
print(transfers['Day'].head(2))

0    2030
1    2027
Name: Year, dtype: object
0    06
1    05
Name: Month, dtype: object
0    30
1    30
Name: Day, dtype: object

In [750]:
# Use re.findall() to create a list of the multple matches of the string
split_date = transfers['transfer_date'].apply(lambda x: re.split(r'-',x))
transfers['Year'] = split_date.apply(lambda x: x[0])
transfers['Month'] = split_date.apply(lambda x: x[1])
transfers['Day'] = split_date.apply(lambda x: x[2])

print(transfers['Year'].head(2))
print(transfers['Month'].head(2))
print(transfers['Day'].head(2))

0    2030
1    2027
Name: Year, dtype: object
0    06
1    05
Name: Month, dtype: object
0    30
1    30
Name: Day, dtype: object

In [751]:
# Use re.sub() to clean string column
transfers['transfer_date'] = transfers['transfer_date'].apply(lambda x: re.sub(r'/',"-",x))
transfers.head(2)

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name,player_upper,player_lower,Date_check,Actual_date,Year,Month,Day
0,467994,2030-06-30,25/26,5621,749,Reggiana,FC Empoli,0.0,700000.0,Luca Belardinelli,LUCA BELARDINELLI,luca belardinelli,2030-06-30,2030-06-30,2030,06,30
1,739277,2027-05-30,26/27,42055,589,Genclik Gücü,Antalyaspor,0.0,NaN,Yannick Nkurunziza,YANNICK NKURUNZIZA,yannick nkurunziza,2027-05-30,2027-05-30,2027,05,30

# Stage 2.10 Encoding

In [752]:
# Convert categorical column using one_hot encoding
all_games = pd.get_dummies(all_games, columns=['Location'])
all_games['Location_Away'] = all_games['Location_Away'].astype(int)
all_games['Location_Home'] = all_games['Location_Home'].astype(int)
all_games.head(5)

,game_id,date,competition_id,season,round,club_id,goals,stadium,attendance,referee,...,competition_type,Result,result,Points,Year,Month,Week_num,Day,Location_Away,Location_Home
0,1026846,2010-06-26,FIWC,2009,Round of 16,3449,2,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,...,national_team_competition,Home Win,W,3,2010,6,5,Saturday,0,1
1,1026847,2010-06-27,FIWC,2009,Round of 16,3437,3,FNB-Stadium,84377.0,Roberto Rosetti,...,national_team_competition,Home Win,W,3,2010,6,6,Sunday,0,1
2,1027001,2010-06-26,FIWC,2009,Round of 16,3505,1,Royal Bafokeng Stadium,34976.0,Viktor Kassai,...,national_team_competition,Away Win,L,0,2010,6,5,Saturday,0,1
3,1027002,2010-06-27,FIWC,2009,Round of 16,3262,4,Free State Stadium,40510.0,Jorge Larrionda,...,national_team_competition,Home Win,W,3,2010,6,6,Sunday,0,1
4,1027048,2010-06-28,FIWC,2009,Round of 16,3379,2,Moses Mabhida Stadion,61962.0,Undiano Mallenco,...,national_team_competition,Home Win,W,3,2010,6,0,Monday,0,1

In [753]:
# Convert categorical column into integer codes (label encoding)
all_games['Result_cat'] = all_games['Result'].astype('category').cat.codes
all_games.head(5)

,game_id,date,competition_id,season,round,club_id,goals,stadium,attendance,referee,...,Result,result,Points,Year,Month,Week_num,Day,Location_Away,Location_Home,Result_cat
0,1026846,2010-06-26,FIWC,2009,Round of 16,3449,2,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,...,Home Win,W,3,2010,6,5,Saturday,0,1,2
1,1026847,2010-06-27,FIWC,2009,Round of 16,3437,3,FNB-Stadium,84377.0,Roberto Rosetti,...,Home Win,W,3,2010,6,6,Sunday,0,1,2
2,1027001,2010-06-26,FIWC,2009,Round of 16,3505,1,Royal Bafokeng Stadium,34976.0,Viktor Kassai,...,Away Win,L,0,2010,6,5,Saturday,0,1,0
3,1027002,2010-06-27,FIWC,2009,Round of 16,3262,4,Free State Stadium,40510.0,Jorge Larrionda,...,Home Win,W,3,2010,6,6,Sunday,0,1,2
4,1027048,2010-06-28,FIWC,2009,Round of 16,3379,2,Moses Mabhida Stadion,61962.0,Undiano Mallenco,...,Home Win,W,3,2010,6,0,Monday,0,1,2